"use strict";
let listOfItems = [];
listOfItems.push("fruits");
listOfItems.push("mountains");
listOfItems.push("riverse");
listOfItems.push("deserts");
listOfItems.push("cities");
listOfItems.push("countries");
listOfItems.push("continents");
console.log(listOfItems);
